### ISSUE TITLE
Instagram Basic API discontinued

### ISSUE THREAD

**Issue by errnesto** [genxbe/kirby3-instagram#13]
As of December 4, 2024 The Instagram Basic is no longer available.  
And for me this means this plugin stoped working.

https://developers.facebook.com/blog/post/2024/09/04/update-on-instagram-basic-display-api/

Is it possible to use this plugin with a different instgram api kind?

**Comment by samzzi** [comment]
Hi @errnesto , I myself won't renew this plugin for the new way of working from instagram. Somebody else in the Kirby community is working on this though. From what I understand he is nearly finished: https://plugins.andkindness.com/socialstar
