### ISSUE TITLE
Can't access Notion page

### ISSUE THREAD

**Issue by thewebprojects** [genxbe/kirby3-instagram#3]
Hello and thank you for taking the time to build this Instagram plugin for Kirby.  I'm trying to get this up and running. There are lots of hoops to jump though.  Your instructions (under 'Authenticate the instagram user and request User token') provides a link to a Notion page, but I cannot access it.  I get a message that states, "You do not have access to GeNx. Please contact an admin to add you as a member."  Please advise.

**Comment by samzzi** [comment]
Ah right, notion changed their links a way back making old links inaccessible. Here's the new one: https://genxbe.notion.site/Link-instagram-with-your-website-9aa72c4961074cb4b4f9b5d1e6322e36 (also changed it in the README file)

It indeed does require jumping through some hoops, that's the pay back for not using a registered app. But it once you jumped all the hoops it works and will keep working 😊

**Comment by thewebprojects** [comment]
Perfect. Thanks!
