### ISSUE TITLE
Error message on running cron job

### ISSUE THREAD

**Issue by MikeHarrison** [genxbe/kirby3-instagram#6]
Hi,

Sorry me again!

I am getting the following error when running the cron job to fetch the instagram posts:

```
Whoops\Exception\ErrorException: unlink(/home/xxxxxx/public_html/assets/instagram/media17860440146772998.jpg): No such file or directory in file /home/xxxxxx/public_html/site/plugins/kirby3-instagram/classes/Instagram.php on line 188
Stack trace:
1. Whoops\Exception\ErrorException->() /home/xxxxxx/public_html/site/plugins/kirby3-instagram/classes/Instagram.php:188
2. unlink() /home/xxxxxx/public_html/site/plugins/kirby3-instagram/classes/Instagram.php:188
3. X\Instagram->fetch() /home/xxxxxx/public_html/site/plugins/kirby3-instagram/fetch.php:27
```

It _looks_ like there is a slash missing on the url between `media` and the filename. Oddly I didn't have this issue when running the site locally, it is only cropping up on the live site.

If you have any thoughts, or ideas of things to try, that would be great.
Thanks!

**Comment by samzzi** [comment]
@MikeHarrison Very odd that I haven't never run into this problem but if I look at the code it does make sense that you get this error 🤔 
I've, presumably, fixed it but since I can't test it (because it just works for me 😛 )... Can you let me know of adding the extra separator helped?

Cheers!

**Comment by MikeHarrison** [comment]
@samzzi that has done the trick, thank you so much for your quick response. It worked fine on my local environment too, it must be a quirk with my production setup somewhere.
