### ISSUE TITLE
Instagram token missing?

### ISSUE THREAD

**Issue by MaluNoPeleke** [genxbe/kirby3-instagram#8]
I have been using this plugin including a cronjob for several months without any issues but since Wednesday I received this error message from the cronjob:

> Exception: There's a problem accessing Instagram. (API access disrupted. Go to the App Dashboard and complete Data Use Checkup.) in file /var/www/virtual/peleke7/[peleke.de/site/plugins/kirby3-instagram/classes/Instagram.php](http://peleke.de/site/plugins/kirby3-instagram/classes/Instagram.php) on line 144
> Stack trace:
>   1. Exception->() /var/www/virtual/peleke7/[peleke.de/site/plugins/kirby3-instagram/classes/Instagram.php:144](http://peleke.de/site/plugins/kirby3-instagram/classes/Instagram.php:144)
>   2. X\Instagram->fetch() /var/www/virtual/peleke7/[peleke.de/site/plugins/kirby3-instagram/fetch.php:27](http://peleke.de/site/plugins/kirby3-instagram/fetch.php:27)

I then clicked on the panel link to recreate the link and allowed access as months before, also without any issues. But when the next cronjob got triggered I received this error message:

> Exception: Instagram token is required. in file /var/www/virtual/peleke7/[peleke.de/site/plugins/kirby3-instagram/fetch.php](http://peleke.de/site/plugins/kirby3-instagram/fetch.php) on line 24
> Stack trace:
>   1. Exception->() /var/www/virtual/peleke7/[peleke.de/site/plugins/kirby3-instagram/fetch.php:24](http://peleke.de/site/plugins/kirby3-instagram/fetch.php:24)

How could I debug/fix it?
Maybe related to #7?

**Comment by samzzi** [comment]
Hi @MaluNoPeleke it seems to me that you need to accept the Meta DUC on your account: https://developers.facebook.com/docs/development/maintaining-data-access/data-use-checkup/

**Comment by MaluNoPeleke** [comment]
Thanks, this seemed to solve the issue indeed.
